name: Build
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  CFLAGS: "-O2 -Wall -Werror"

jobs:
  ci:
    permissions:
      contents: read
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: true
      matrix:
        compiler:
          - CC: gcc
          - CC: clang
    name: "Build (${{ matrix.compiler.CC }})"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Build
        run: make -C tests CC=${{ matrix.compiler.CC }}
